import 'package:flutter/widgets.dart';
import 'package:optimus_icons/src/optimus_icons.dart';

// NB: DO NOT EDIT! This file is auto-generated. See utils/gen_icons.dart

class IconDetails {
  const IconDetails(this.data, this.name);
  final IconData data;
  final String name;
}

const optimusIcons = <IconDetails>[
  IconDetails(OptimusIcons.accounting_ledger_24, 'accounting_ledger_24'),
  IconDetails(OptimusIcons.accounting_ledger, 'accounting_ledger'),
  IconDetails(OptimusIcons.accounting_report_24, 'accounting_report_24'),
  IconDetails(OptimusIcons.accounting_report, 'accounting_report'),
  IconDetails(OptimusIcons.action_log_24, 'action_log_24'),
  IconDetails(OptimusIcons.action_log, 'action_log'),
  IconDetails(OptimusIcons.activity_report_24, 'activity_report_24'),
  IconDetails(OptimusIcons.activity_report, 'activity_report'),
  IconDetails(OptimusIcons.add_24, 'add_24'),
  IconDetails(OptimusIcons.add_customer_24, 'add_customer_24'),
  IconDetails(OptimusIcons.add_customer, 'add_customer'),
  IconDetails(OptimusIcons.add_photo_24, 'add_photo_24'),
  IconDetails(OptimusIcons.add_photo, 'add_photo'),
  IconDetails(OptimusIcons.add, 'add'),
  IconDetails(OptimusIcons.ai_24, 'ai_24'),
  IconDetails(OptimusIcons.ai, 'ai'),
  IconDetails(OptimusIcons.alert_circle_24, 'alert_circle_24'),
  IconDetails(OptimusIcons.alert_circle, 'alert_circle'),
  IconDetails(OptimusIcons.analytics_24, 'analytics_24'),
  IconDetails(OptimusIcons.analytics, 'analytics'),
  IconDetails(OptimusIcons.archive_24, 'archive_24'),
  IconDetails(OptimusIcons.archive, 'archive'),
  IconDetails(OptimusIcons.arrivals_24, 'arrivals_24'),
  IconDetails(OptimusIcons.arrivals, 'arrivals'),
  IconDetails(OptimusIcons.arrow_down_24, 'arrow_down_24'),
  IconDetails(OptimusIcons.arrow_down, 'arrow_down'),
  IconDetails(OptimusIcons.arrow_joined_24, 'arrow_joined_24'),
  IconDetails(OptimusIcons.arrow_joined, 'arrow_joined'),
  IconDetails(OptimusIcons.arrow_left_24, 'arrow_left_24'),
  IconDetails(OptimusIcons.arrow_left, 'arrow_left'),
  IconDetails(OptimusIcons.arrow_right_24, 'arrow_right_24'),
  IconDetails(OptimusIcons.arrow_right, 'arrow_right'),
  IconDetails(OptimusIcons.arrow_trend_down_24_24, 'arrow_trend_down_24_24'),
  IconDetails(OptimusIcons.arrow_trend_up_24_24, 'arrow_trend_up_24_24'),
  IconDetails(OptimusIcons.arrow_up_24, 'arrow_up_24'),
  IconDetails(OptimusIcons.arrow_up, 'arrow_up'),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_1_24,
    'arrow_counter_clockwise_1_24',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_1,
    'arrow_counter_clockwise_1',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_2_24,
    'arrow_counter_clockwise_2_24',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_2,
    'arrow_counter_clockwise_2',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_3_24,
    'arrow_counter_clockwise_3_24',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_3,
    'arrow_counter_clockwise_3',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_4_24,
    'arrow_counter_clockwise_4_24',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_4,
    'arrow_counter_clockwise_4',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_5_24,
    'arrow_counter_clockwise_5_24',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_5,
    'arrow_counter_clockwise_5',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_6_24,
    'arrow_counter_clockwise_6_24',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_6,
    'arrow_counter_clockwise_6',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_7_24,
    'arrow_counter_clockwise_7_24',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_7,
    'arrow_counter_clockwise_7',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_8_24,
    'arrow_counter_clockwise_8_24',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_8,
    'arrow_counter_clockwise_8',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_9_24,
    'arrow_counter_clockwise_9_24',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_9_plus_24,
    'arrow_counter_clockwise_9_plus_24',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_9_plus,
    'arrow_counter_clockwise_9_plus',
  ),
  IconDetails(
    OptimusIcons.arrow_counter_clockwise_9,
    'arrow_counter_clockwise_9',
  ),
  IconDetails(OptimusIcons.assign_24, 'assign_24'),
  IconDetails(OptimusIcons.assign, 'assign'),
  IconDetails(OptimusIcons.at_mention_24, 'at_mention_24'),
  IconDetails(OptimusIcons.autosize_24, 'autosize_24'),
  IconDetails(OptimusIcons.autosize, 'autosize'),
  IconDetails(OptimusIcons.availability_24, 'availability_24'),
  IconDetails(OptimusIcons.availability, 'availability'),
  IconDetails(OptimusIcons.available_dates_24, 'available_dates_24'),
  IconDetails(OptimusIcons.available_dates, 'available_dates'),
  IconDetails(OptimusIcons.baby_cot_24, 'baby_cot_24'),
  IconDetails(OptimusIcons.baby_cot, 'baby_cot'),
  IconDetails(OptimusIcons.backward_24, 'backward_24'),
  IconDetails(OptimusIcons.backward_more_24, 'backward_more_24'),
  IconDetails(OptimusIcons.backward_more, 'backward_more'),
  IconDetails(OptimusIcons.backward, 'backward'),
  IconDetails(OptimusIcons.bathroom_24, 'bathroom_24'),
  IconDetails(OptimusIcons.bathroom, 'bathroom'),
  IconDetails(OptimusIcons.bi_24, 'bi_24'),
  IconDetails(OptimusIcons.bike_24, 'bike_24'),
  IconDetails(OptimusIcons.bike, 'bike'),
  IconDetails(OptimusIcons.bills_invoices_24, 'bills_invoices_24'),
  IconDetails(OptimusIcons.bills_invoices, 'bills_invoices'),
  IconDetails(OptimusIcons.birthday_24, 'birthday_24'),
  IconDetails(OptimusIcons.birthday, 'birthday'),
  IconDetails(OptimusIcons.blacklist_24, 'blacklist_24'),
  IconDetails(OptimusIcons.blacklist, 'blacklist'),
  IconDetails(OptimusIcons.bold_24, 'bold_24'),
  IconDetails(OptimusIcons.briefcase_24, 'briefcase_24'),
  IconDetails(OptimusIcons.briefcase, 'briefcase'),
  IconDetails(OptimusIcons.broom_24, 'broom_24'),
  IconDetails(OptimusIcons.broom, 'broom'),
  IconDetails(OptimusIcons.building_plus_24, 'building_plus_24'),
  IconDetails(OptimusIcons.building_plus, 'building_plus'),
  IconDetails(OptimusIcons.bulb_stars_24, 'bulb_stars_24'),
  IconDetails(OptimusIcons.bulb_stars, 'bulb_stars'),
  IconDetails(OptimusIcons.bulk_edit_24, 'bulk_edit_24'),
  IconDetails(OptimusIcons.bulk_edit, 'bulk_edit'),
  IconDetails(OptimusIcons.bus_24, 'bus_24'),
  IconDetails(OptimusIcons.bus, 'bus'),
  IconDetails(OptimusIcons.calendar_24, 'calendar_24'),
  IconDetails(OptimusIcons.calendar_day_24, 'calendar_day_24'),
  IconDetails(OptimusIcons.calendar_month_24, 'calendar_month_24'),
  IconDetails(OptimusIcons.calendar_stars_24, 'calendar_stars_24'),
  IconDetails(OptimusIcons.calendar_stars, 'calendar_stars'),
  IconDetails(OptimusIcons.calendar_week_24, 'calendar_week_24'),
  IconDetails(OptimusIcons.calendar, 'calendar'),
  IconDetails(OptimusIcons.camera_24, 'camera_24'),
  IconDetails(OptimusIcons.camera, 'camera'),
  IconDetails(OptimusIcons.campervan_24, 'campervan_24'),
  IconDetails(OptimusIcons.campervan, 'campervan'),
  IconDetails(OptimusIcons.camping_pitch_24, 'camping_pitch_24'),
  IconDetails(OptimusIcons.camping_pitch, 'camping_pitch'),
  IconDetails(OptimusIcons.cancel_square_24, 'cancel_square_24'),
  IconDetails(OptimusIcons.cancel_square, 'cancel_square'),
  IconDetails(OptimusIcons.caravan_24, 'caravan_24'),
  IconDetails(OptimusIcons.caravan, 'caravan'),
  IconDetails(OptimusIcons.card_check_24, 'card_check_24'),
  IconDetails(OptimusIcons.card_check, 'card_check'),
  IconDetails(OptimusIcons.card_keys_24, 'card_keys_24'),
  IconDetails(OptimusIcons.card_keys, 'card_keys'),
  IconDetails(OptimusIcons.card_nfc_24, 'card_nfc_24'),
  IconDetails(OptimusIcons.card_nfc, 'card_nfc'),
  IconDetails(OptimusIcons.caret_filled_down_24, 'caret_filled_down_24'),
  IconDetails(OptimusIcons.caret_filled_down, 'caret_filled_down'),
  IconDetails(OptimusIcons.caret_filled_up_24, 'caret_filled_up_24'),
  IconDetails(OptimusIcons.caret_filled_up, 'caret_filled_up'),
  IconDetails(OptimusIcons.cash_payment_24, 'cash_payment_24'),
  IconDetails(OptimusIcons.cash_payment, 'cash_payment'),
  IconDetails(OptimusIcons.cashier_24, 'cashier_24'),
  IconDetails(OptimusIcons.cashier, 'cashier'),
  IconDetails(OptimusIcons.cashlist_24, 'cashlist_24'),
  IconDetails(OptimusIcons.cashlist, 'cashlist'),
  IconDetails(OptimusIcons.channel_manager_24, 'channel_manager_24'),
  IconDetails(OptimusIcons.channel_manager, 'channel_manager'),
  IconDetails(OptimusIcons.charge_24, 'charge_24'),
  IconDetails(OptimusIcons.charge, 'charge'),
  IconDetails(OptimusIcons.chargeable_24, 'chargeable_24'),
  IconDetails(OptimusIcons.chargeable, 'chargeable'),
  IconDetails(OptimusIcons.chargeback_24, 'chargeback_24'),
  IconDetails(OptimusIcons.chargeback, 'chargeback'),
  IconDetails(OptimusIcons.checkbox_empty_24, 'checkbox_empty_24'),
  IconDetails(OptimusIcons.checkbox_empty, 'checkbox_empty'),
  IconDetails(OptimusIcons.checkbox_minus, 'checkbox_minus'),
  IconDetails(OptimusIcons.checkbox_plus, 'checkbox_plus'),
  IconDetails(OptimusIcons.checkbox_tick_24, 'checkbox_tick_24'),
  IconDetails(OptimusIcons.checkbox_tick, 'checkbox_tick'),
  IconDetails(OptimusIcons.checked_in_24, 'checked_in_24'),
  IconDetails(OptimusIcons.checked_in, 'checked_in'),
  IconDetails(OptimusIcons.checked_out_24, 'checked_out_24'),
  IconDetails(OptimusIcons.checked_out, 'checked_out'),
  IconDetails(OptimusIcons.checkin_24, 'checkin_24'),
  IconDetails(OptimusIcons.checkin, 'checkin'),
  IconDetails(OptimusIcons.checkout_24, 'checkout_24'),
  IconDetails(OptimusIcons.checkout, 'checkout'),
  IconDetails(OptimusIcons.chevron_down_24, 'chevron_down_24'),
  IconDetails(OptimusIcons.chevron_down, 'chevron_down'),
  IconDetails(OptimusIcons.chevron_left_24, 'chevron_left_24'),
  IconDetails(OptimusIcons.chevron_left, 'chevron_left'),
  IconDetails(OptimusIcons.chevron_right_24, 'chevron_right_24'),
  IconDetails(OptimusIcons.chevron_right, 'chevron_right'),
  IconDetails(OptimusIcons.chevron_up_24, 'chevron_up_24'),
  IconDetails(OptimusIcons.chevron_up, 'chevron_up'),
  IconDetails(OptimusIcons.child_head_24, 'child_head_24'),
  IconDetails(OptimusIcons.child_head, 'child_head'),
  IconDetails(OptimusIcons.city_24, 'city_24'),
  IconDetails(OptimusIcons.city, 'city'),
  IconDetails(OptimusIcons.clear_selection_24, 'clear_selection_24'),
  IconDetails(OptimusIcons.clear_selection, 'clear_selection'),
  IconDetails(OptimusIcons.collapse_24, 'collapse_24'),
  IconDetails(OptimusIcons.collapse_all_24, 'collapse_all_24'),
  IconDetails(OptimusIcons.collapse_all, 'collapse_all'),
  IconDetails(OptimusIcons.collapse, 'collapse'),
  IconDetails(OptimusIcons.companies, 'companies'),
  IconDetails(OptimusIcons.complaint_24, 'complaint_24'),
  IconDetails(OptimusIcons.complaint, 'complaint'),
  IconDetails(OptimusIcons.configuration_24, 'configuration_24'),
  IconDetails(OptimusIcons.configuration, 'configuration'),
  IconDetails(OptimusIcons.connect_24, 'connect_24'),
  IconDetails(OptimusIcons.connect, 'connect'),
  IconDetails(OptimusIcons.contract, 'contract'),
  IconDetails(OptimusIcons.controls_24, 'controls_24'),
  IconDetails(OptimusIcons.controls, 'controls'),
  IconDetails(OptimusIcons.copy_24, 'copy_24'),
  IconDetails(OptimusIcons.copy, 'copy'),
  IconDetails(OptimusIcons.countries_24, 'countries_24'),
  IconDetails(OptimusIcons.countries, 'countries'),
  IconDetails(OptimusIcons.covid_protection_24, 'covid_protection_24'),
  IconDetails(OptimusIcons.covid_protection, 'covid_protection'),
  IconDetails(OptimusIcons.credit_card_file_24, 'credit_card_file_24'),
  IconDetails(OptimusIcons.credit_card_file, 'credit_card_file'),
  IconDetails(OptimusIcons.credit_card_report_24, 'credit_card_report_24'),
  IconDetails(OptimusIcons.credit_card_report, 'credit_card_report'),
  IconDetails(OptimusIcons.crib_24, 'crib_24'),
  IconDetails(OptimusIcons.crib, 'crib'),
  IconDetails(OptimusIcons.cross_close_24, 'cross_close_24'),
  IconDetails(OptimusIcons.cross_close, 'cross_close'),
  IconDetails(OptimusIcons.cultures_24, 'cultures_24'),
  IconDetails(OptimusIcons.cultures, 'cultures'),
  IconDetails(OptimusIcons.currency_switch_24, 'currency_switch_24'),
  IconDetails(OptimusIcons.currency_switch, 'currency_switch'),
  IconDetails(OptimusIcons.custom_link_24, 'custom_link_24'),
  IconDetails(OptimusIcons.custom_link_item_24, 'custom_link_item_24'),
  IconDetails(OptimusIcons.custom_link_item, 'custom_link_item'),
  IconDetails(OptimusIcons.custom_link, 'custom_link'),
  IconDetails(OptimusIcons.customer_profiles_24, 'customer_profiles_24'),
  IconDetails(OptimusIcons.customer_profiles, 'customer_profiles'),
  IconDetails(OptimusIcons.customer_success_24, 'customer_success_24'),
  IconDetails(OptimusIcons.customer_success, 'customer_success'),
  IconDetails(OptimusIcons.dashboard_24, 'dashboard_24'),
  IconDetails(OptimusIcons.dashboard, 'dashboard'),
  IconDetails(OptimusIcons.day, 'day'),
  IconDetails(OptimusIcons.delete_24, 'delete_24'),
  IconDetails(OptimusIcons.delete, 'delete'),
  IconDetails(OptimusIcons.departures_24, 'departures_24'),
  IconDetails(OptimusIcons.departures, 'departures'),
  IconDetails(OptimusIcons.deployments_24, 'deployments_24'),
  IconDetails(OptimusIcons.deployments, 'deployments'),
  IconDetails(OptimusIcons.desk_24, 'desk_24'),
  IconDetails(OptimusIcons.desk, 'desk'),
  IconDetails(OptimusIcons.device_command_24, 'device_command_24'),
  IconDetails(OptimusIcons.device_command, 'device_command'),
  IconDetails(OptimusIcons.disability_24, 'disability_24'),
  IconDetails(OptimusIcons.disability, 'disability'),
  IconDetails(OptimusIcons.disable_24, 'disable_24'),
  IconDetails(OptimusIcons.disable, 'disable'),
  IconDetails(OptimusIcons.dollar_arrow_down_24, 'dollar_arrow_down_24'),
  IconDetails(OptimusIcons.dollar_arrow_down, 'dollar_arrow_down'),
  IconDetails(OptimusIcons.done_24, 'done_24'),
  IconDetails(OptimusIcons.done_circle_24, 'done_circle_24'),
  IconDetails(OptimusIcons.done_circle, 'done_circle'),
  IconDetails(OptimusIcons.done, 'done'),
  IconDetails(OptimusIcons.door_hanger_24, 'door_hanger_24'),
  IconDetails(OptimusIcons.door_hanger, 'door_hanger'),
  IconDetails(OptimusIcons.dot_filled_24, 'dot_filled_24'),
  IconDetails(OptimusIcons.dot_filled, 'dot_filled'),
  IconDetails(OptimusIcons.double_bed_24, 'double_bed_24'),
  IconDetails(OptimusIcons.double_bed, 'double_bed'),
  IconDetails(OptimusIcons.download_24, 'download_24'),
  IconDetails(OptimusIcons.download, 'download'),
  IconDetails(OptimusIcons.draggable_24, 'draggable_24'),
  IconDetails(OptimusIcons.draggable, 'draggable'),
  IconDetails(OptimusIcons.driving_licence_24, 'driving_licence_24'),
  IconDetails(OptimusIcons.driving_licence, 'driving_licence'),
  IconDetails(OptimusIcons.edit_24, 'edit_24'),
  IconDetails(OptimusIcons.edit, 'edit'),
  IconDetails(OptimusIcons.education_24, 'education_24'),
  IconDetails(OptimusIcons.education, 'education'),
  IconDetails(OptimusIcons.email_queue_24, 'email_queue_24'),
  IconDetails(OptimusIcons.email_queue, 'email_queue'),
  IconDetails(OptimusIcons.email_queues_24, 'email_queues_24'),
  IconDetails(OptimusIcons.email_queues, 'email_queues'),
  IconDetails(OptimusIcons.employees_24, 'employees_24'),
  IconDetails(OptimusIcons.employees, 'employees'),
  IconDetails(OptimusIcons.enterprise_snapshot_24, 'enterprise_snapshot_24'),
  IconDetails(OptimusIcons.enterprise_snapshot, 'enterprise_snapshot'),
  IconDetails(OptimusIcons.error_circle_24, 'error_circle_24'),
  IconDetails(OptimusIcons.error_circle, 'error_circle'),
  IconDetails(OptimusIcons.execute_24, 'execute_24'),
  IconDetails(OptimusIcons.execute_merchant_24, 'execute_merchant_24'),
  IconDetails(OptimusIcons.execute_merchant, 'execute_merchant'),
  IconDetails(OptimusIcons.execute, 'execute'),
  IconDetails(OptimusIcons.expand_24, 'expand_24'),
  IconDetails(OptimusIcons.expand_all_24, 'expand_all_24'),
  IconDetails(OptimusIcons.expand_all, 'expand_all'),
  IconDetails(OptimusIcons.expand, 'expand'),
  IconDetails(OptimusIcons.experiences_24, 'experiences_24'),
  IconDetails(OptimusIcons.experiences, 'experiences'),
  IconDetails(OptimusIcons.export_schedule_24, 'export_schedule_24'),
  IconDetails(OptimusIcons.export_schedule, 'export_schedule'),
  IconDetails(OptimusIcons.exports_24, 'exports_24'),
  IconDetails(OptimusIcons.exports, 'exports'),
  IconDetails(OptimusIcons.external_link_24, 'external_link_24'),
  IconDetails(OptimusIcons.external_link, 'external_link'),
  IconDetails(OptimusIcons.external_payment_24, 'external_payment_24'),
  IconDetails(OptimusIcons.external_payment, 'external_payment'),
  IconDetails(OptimusIcons.extrabed_24, 'extrabed_24'),
  IconDetails(OptimusIcons.extrabed, 'extrabed'),
  IconDetails(OptimusIcons.face_happy_24, 'face_happy_24'),
  IconDetails(OptimusIcons.face_happy, 'face_happy'),
  IconDetails(OptimusIcons.face_id_24, 'face_id_24'),
  IconDetails(OptimusIcons.face_id, 'face_id'),
  IconDetails(OptimusIcons.face_sad_24, 'face_sad_24'),
  IconDetails(OptimusIcons.face_sad, 'face_sad'),
  IconDetails(OptimusIcons.facebook_24, 'facebook_24'),
  IconDetails(OptimusIcons.facebook, 'facebook'),
  IconDetails(OptimusIcons.fast_backward_simple_24, 'fast_backward_simple_24'),
  IconDetails(OptimusIcons.fast_backward_simple, 'fast_backward_simple'),
  IconDetails(OptimusIcons.fast_forward_simple_24, 'fast_forward_simple_24'),
  IconDetails(OptimusIcons.fast_forward_simple, 'fast_forward_simple'),
  IconDetails(OptimusIcons.features_24, 'features_24'),
  IconDetails(OptimusIcons.features, 'features'),
  IconDetails(OptimusIcons.female_24, 'female_24'),
  IconDetails(OptimusIcons.female, 'female'),
  IconDetails(OptimusIcons.file_check_24_24, 'file_check_24_24'),
  IconDetails(OptimusIcons.filter_24, 'filter_24'),
  IconDetails(OptimusIcons.filter, 'filter'),
  IconDetails(OptimusIcons.finance_24, 'finance_24'),
  IconDetails(OptimusIcons.finance, 'finance'),
  IconDetails(OptimusIcons.fiscal_report_24, 'fiscal_report_24'),
  IconDetails(OptimusIcons.fiscal_report, 'fiscal_report'),
  IconDetails(OptimusIcons.floppy_disc_24, 'floppy_disc_24'),
  IconDetails(OptimusIcons.floppy_disc, 'floppy_disc'),
  IconDetails(OptimusIcons.folder_closed_24, 'folder_closed_24'),
  IconDetails(OptimusIcons.folder_closed, 'folder_closed'),
  IconDetails(OptimusIcons.folder_opened_24, 'folder_opened_24'),
  IconDetails(OptimusIcons.folder_opened, 'folder_opened'),
  IconDetails(OptimusIcons.food_24, 'food_24'),
  IconDetails(OptimusIcons.food, 'food'),
  IconDetails(OptimusIcons.forum_outline_24, 'forum_outline_24'),
  IconDetails(OptimusIcons.forum_outline, 'forum_outline'),
  IconDetails(OptimusIcons.forward_24, 'forward_24'),
  IconDetails(OptimusIcons.forward_more_24, 'forward_more_24'),
  IconDetails(OptimusIcons.forward_more, 'forward_more'),
  IconDetails(OptimusIcons.forward, 'forward'),
  IconDetails(OptimusIcons.free_24, 'free_24'),
  IconDetails(OptimusIcons.free, 'free'),
  IconDetails(OptimusIcons.friend_family_24, 'friend_family_24'),
  IconDetails(OptimusIcons.friend_family, 'friend_family'),
  IconDetails(OptimusIcons.ftp_24, 'ftp_24'),
  IconDetails(OptimusIcons.ftp, 'ftp'),
  IconDetails(OptimusIcons.gateway_payments_24, 'gateway_payments_24'),
  IconDetails(OptimusIcons.gateway_payments, 'gateway_payments'),
  IconDetails(OptimusIcons.gift_24, 'gift_24'),
  IconDetails(OptimusIcons.gift, 'gift'),
  IconDetails(OptimusIcons.guest_in_house_24, 'guest_in_house_24'),
  IconDetails(OptimusIcons.guest_in_house, 'guest_in_house'),
  IconDetails(OptimusIcons.guides_24, 'guides_24'),
  IconDetails(OptimusIcons.guides, 'guides'),
  IconDetails(OptimusIcons.help_24, 'help_24'),
  IconDetails(OptimusIcons.help_center_24, 'help_center_24'),
  IconDetails(OptimusIcons.help_center, 'help_center'),
  IconDetails(OptimusIcons.help, 'help'),
  IconDetails(OptimusIcons.hide_24, 'hide_24'),
  IconDetails(OptimusIcons.hide, 'hide'),
  IconDetails(OptimusIcons.home_24, 'home_24'),
  IconDetails(OptimusIcons.home_empty_24, 'home_empty_24'),
  IconDetails(OptimusIcons.home_empty, 'home_empty'),
  IconDetails(OptimusIcons.home, 'home'),
  IconDetails(OptimusIcons.hourglass_24, 'hourglass_24'),
  IconDetails(OptimusIcons.hourglass, 'hourglass'),
  IconDetails(OptimusIcons.house_use_24, 'house_use_24'),
  IconDetails(OptimusIcons.house_use, 'house_use'),
  IconDetails(OptimusIcons.id_card_24, 'id_card_24'),
  IconDetails(OptimusIcons.id_card, 'id_card'),
  IconDetails(OptimusIcons.import_24, 'import_24'),
  IconDetails(OptimusIcons.import_customers_24, 'import_customers_24'),
  IconDetails(OptimusIcons.import_customers, 'import_customers'),
  IconDetails(OptimusIcons.import_icon, 'import_icon'),
  IconDetails(OptimusIcons.important_24, 'important_24'),
  IconDetails(OptimusIcons.important, 'important'),
  IconDetails(OptimusIcons.imports_24, 'imports_24'),
  IconDetails(OptimusIcons.imports, 'imports'),
  IconDetails(OptimusIcons.improvement_24, 'improvement_24'),
  IconDetails(OptimusIcons.improvement, 'improvement'),
  IconDetails(OptimusIcons.info_24, 'info_24'),
  IconDetails(OptimusIcons.info, 'info'),
  IconDetails(OptimusIcons.installations_24, 'installations_24'),
  IconDetails(OptimusIcons.installations, 'installations'),
  IconDetails(OptimusIcons.integration_partners_24, 'integration_partners_24'),
  IconDetails(OptimusIcons.integration_partners, 'integration_partners'),
  IconDetails(OptimusIcons.integrations_24, 'integrations_24'),
  IconDetails(OptimusIcons.integrations, 'integrations'),
  IconDetails(OptimusIcons.inventory_updates_24, 'inventory_updates_24'),
  IconDetails(OptimusIcons.inventory_updates, 'inventory_updates'),
  IconDetails(OptimusIcons.italic_24, 'italic_24'),
  IconDetails(OptimusIcons.items_24, 'items_24'),
  IconDetails(OptimusIcons.items, 'items'),
  IconDetails(OptimusIcons.jobs_24, 'jobs_24'),
  IconDetails(OptimusIcons.jobs, 'jobs'),
  IconDetails(OptimusIcons.key_24, 'key_24'),
  IconDetails(OptimusIcons.key, 'key'),
  IconDetails(OptimusIcons.language_switch_24, 'language_switch_24'),
  IconDetails(OptimusIcons.language_switch, 'language_switch'),
  IconDetails(OptimusIcons.languages_24, 'languages_24'),
  IconDetails(OptimusIcons.languages, 'languages'),
  IconDetails(OptimusIcons.layout_grid_24, 'layout_grid_24'),
  IconDetails(OptimusIcons.layout_grid, 'layout_grid'),
  IconDetails(OptimusIcons.legal_environments_24, 'legal_environments_24'),
  IconDetails(OptimusIcons.legal_environments, 'legal_environments'),
  IconDetails(OptimusIcons.lightning_bolt_24, 'lightning_bolt_24'),
  IconDetails(OptimusIcons.lightning_bolt, 'lightning_bolt'),
  IconDetails(OptimusIcons.linkedin_24, 'linkedin_24'),
  IconDetails(OptimusIcons.linkedin, 'linkedin'),
  IconDetails(OptimusIcons.list_ordered_24, 'list_ordered_24'),
  IconDetails(OptimusIcons.location_24, 'location_24'),
  IconDetails(OptimusIcons.location, 'location'),
  IconDetails(OptimusIcons.lock_24, 'lock_24'),
  IconDetails(OptimusIcons.lock, 'lock'),
  IconDetails(OptimusIcons.logout_24, 'logout_24'),
  IconDetails(OptimusIcons.logout, 'logout'),
  IconDetails(OptimusIcons.loyalty_24, 'loyalty_24'),
  IconDetails(OptimusIcons.loyalty, 'loyalty'),
  IconDetails(OptimusIcons.luggage_24, 'luggage_24'),
  IconDetails(OptimusIcons.luggage, 'luggage'),
  IconDetails(OptimusIcons.magic_24, 'magic_24'),
  IconDetails(OptimusIcons.magic, 'magic'),
  IconDetails(OptimusIcons.mails_24, 'mails_24'),
  IconDetails(OptimusIcons.mails, 'mails'),
  IconDetails(OptimusIcons.make_default_24, 'make_default_24'),
  IconDetails(OptimusIcons.make_default, 'make_default'),
  IconDetails(OptimusIcons.male_24, 'male_24'),
  IconDetails(OptimusIcons.male, 'male'),
  IconDetails(OptimusIcons.manager_report_24, 'manager_report_24'),
  IconDetails(OptimusIcons.manager_report, 'manager_report'),
  IconDetails(OptimusIcons.mark_as_read_24, 'mark_as_read_24'),
  IconDetails(OptimusIcons.mark_as_read, 'mark_as_read'),
  IconDetails(OptimusIcons.marketplace_24, 'marketplace_24'),
  IconDetails(OptimusIcons.marketplace, 'marketplace'),
  IconDetails(OptimusIcons.media_24, 'media_24'),
  IconDetails(OptimusIcons.media_playback_pause_24, 'media_playback_pause_24'),
  IconDetails(OptimusIcons.media_playback_pause, 'media_playback_pause'),
  IconDetails(OptimusIcons.media_playback_play_24, 'media_playback_play_24'),
  IconDetails(OptimusIcons.media_playback_play, 'media_playback_play'),
  IconDetails(OptimusIcons.media, 'media'),
  IconDetails(OptimusIcons.megaphone_24, 'megaphone_24'),
  IconDetails(OptimusIcons.megaphone, 'megaphone'),
  IconDetails(OptimusIcons.menu_24, 'menu_24'),
  IconDetails(OptimusIcons.menu_arrow_left_24, 'menu_arrow_left_24'),
  IconDetails(OptimusIcons.menu_arrow_left, 'menu_arrow_left'),
  IconDetails(OptimusIcons.menu_arrow_right_24, 'menu_arrow_right_24'),
  IconDetails(OptimusIcons.menu_arrow_right, 'menu_arrow_right'),
  IconDetails(OptimusIcons.menu, 'menu'),
  IconDetails(OptimusIcons.merchant_24, 'merchant_24'),
  IconDetails(OptimusIcons.merchant, 'merchant'),
  IconDetails(OptimusIcons.message_24, 'message_24'),
  IconDetails(OptimusIcons.message, 'message'),
  IconDetails(OptimusIcons.messages_plural_24, 'messages_plural_24'),
  IconDetails(OptimusIcons.messages_plural, 'messages_plural'),
  IconDetails(OptimusIcons.mews_logo_24, 'mews_logo_24'),
  IconDetails(OptimusIcons.mews_logo, 'mews_logo'),
  IconDetails(OptimusIcons.microphone_24, 'microphone_24'),
  IconDetails(OptimusIcons.microphone, 'microphone'),
  IconDetails(OptimusIcons.military_24, 'military_24'),
  IconDetails(OptimusIcons.military, 'military'),
  IconDetails(OptimusIcons.minus_24, 'minus_24'),
  IconDetails(OptimusIcons.minus_simple_24, 'minus_simple_24'),
  IconDetails(OptimusIcons.minus_simple, 'minus_simple'),
  IconDetails(OptimusIcons.minus, 'minus'),
  IconDetails(OptimusIcons.month, 'month'),
  IconDetails(OptimusIcons.more_24, 'more_24'),
  IconDetails(OptimusIcons.more, 'more'),
  IconDetails(OptimusIcons.move_24, 'move_24'),
  IconDetails(OptimusIcons.move_payment_24, 'move_payment_24'),
  IconDetails(
    OptimusIcons.move_payment_horizontal_24,
    'move_payment_horizontal_24',
  ),
  IconDetails(OptimusIcons.move_payment_horizontal, 'move_payment_horizontal'),
  IconDetails(OptimusIcons.move_payment, 'move_payment'),
  IconDetails(OptimusIcons.move, 'move'),
  IconDetails(OptimusIcons.nonbreaking_space_24, 'nonbreaking_space_24'),
  IconDetails(OptimusIcons.nonbreaking_space, 'nonbreaking_space'),
  IconDetails(OptimusIcons.notes_24, 'notes_24'),
  IconDetails(OptimusIcons.notes, 'notes'),
  IconDetails(OptimusIcons.notifications_24, 'notifications_24'),
  IconDetails(OptimusIcons.notifications, 'notifications'),
  IconDetails(OptimusIcons.occupancy_24, 'occupancy_24'),
  IconDetails(OptimusIcons.occupancy, 'occupancy'),
  IconDetails(OptimusIcons.operations_24, 'operations_24'),
  IconDetails(OptimusIcons.operations, 'operations'),
  IconDetails(OptimusIcons.out_of_order_24, 'out_of_order_24'),
  IconDetails(OptimusIcons.out_of_order, 'out_of_order'),
  IconDetails(OptimusIcons.paperclip_24, 'paperclip_24'),
  IconDetails(OptimusIcons.passport_24, 'passport_24'),
  IconDetails(OptimusIcons.passport, 'passport'),
  IconDetails(OptimusIcons.past_shifts_24, 'past_shifts_24'),
  IconDetails(OptimusIcons.past_shifts, 'past_shifts'),
  IconDetails(OptimusIcons.paymaster_24, 'paymaster_24'),
  IconDetails(OptimusIcons.paymaster, 'paymaster'),
  IconDetails(OptimusIcons.payment_attempts_24, 'payment_attempts_24'),
  IconDetails(OptimusIcons.payment_attempts, 'payment_attempts'),
  IconDetails(OptimusIcons.payment_card_24, 'payment_card_24'),
  IconDetails(OptimusIcons.payment_card, 'payment_card'),
  IconDetails(OptimusIcons.payment_report_24, 'payment_report_24'),
  IconDetails(OptimusIcons.payment_report, 'payment_report'),
  IconDetails(OptimusIcons.payment_request_24, 'payment_request_24'),
  IconDetails(OptimusIcons.payment_request, 'payment_request'),
  IconDetails(OptimusIcons.payments_24, 'payments_24'),
  IconDetails(OptimusIcons.payments, 'payments'),
  IconDetails(OptimusIcons.phone_24, 'phone_24'),
  IconDetails(OptimusIcons.phone, 'phone'),
  IconDetails(OptimusIcons.photo_expand_24, 'photo_expand_24'),
  IconDetails(OptimusIcons.photo_expand, 'photo_expand'),
  IconDetails(OptimusIcons.pin_24, 'pin_24'),
  IconDetails(OptimusIcons.pin, 'pin'),
  IconDetails(OptimusIcons.places_24, 'places_24'),
  IconDetails(OptimusIcons.places_pin_24, 'places_pin_24'),
  IconDetails(OptimusIcons.places_pin, 'places_pin'),
  IconDetails(OptimusIcons.places, 'places'),
  IconDetails(OptimusIcons.plane_24, 'plane_24'),
  IconDetails(OptimusIcons.plane, 'plane'),
  IconDetails(OptimusIcons.platform_migrations_24, 'platform_migrations_24'),
  IconDetails(OptimusIcons.platform_migrations, 'platform_migrations'),
  IconDetails(OptimusIcons.plus_24, 'plus_24'),
  IconDetails(OptimusIcons.plus_simple_24, 'plus_simple_24'),
  IconDetails(OptimusIcons.plus_simple, 'plus_simple'),
  IconDetails(OptimusIcons.plus, 'plus'),
  IconDetails(OptimusIcons.posting_journal_24, 'posting_journal_24'),
  IconDetails(OptimusIcons.posting_journal, 'posting_journal'),
  IconDetails(OptimusIcons.power_bi, 'power_bi'),
  IconDetails(OptimusIcons.preauthorization_24, 'preauthorization_24'),
  IconDetails(OptimusIcons.preauthorization, 'preauthorization'),
  IconDetails(OptimusIcons.pricing_24, 'pricing_24'),
  IconDetails(OptimusIcons.pricing, 'pricing'),
  IconDetails(OptimusIcons.print_24, 'print_24'),
  IconDetails(OptimusIcons.print_pdf_24, 'print_pdf_24'),
  IconDetails(OptimusIcons.print_pdf, 'print_pdf'),
  IconDetails(OptimusIcons.print, 'print'),
  IconDetails(OptimusIcons.problematic_24, 'problematic_24'),
  IconDetails(OptimusIcons.problematic, 'problematic'),
  IconDetails(OptimusIcons.product_24, 'product_24'),
  IconDetails(OptimusIcons.product_report_24, 'product_report_24'),
  IconDetails(OptimusIcons.product_report, 'product_report'),
  IconDetails(OptimusIcons.profile_24, 'profile_24'),
  IconDetails(OptimusIcons.profile, 'profile'),
  IconDetails(OptimusIcons.profiles_24, 'profiles_24'),
  IconDetails(OptimusIcons.profiles, 'profiles'),
  IconDetails(OptimusIcons.property_24, 'property_24'),
  IconDetails(OptimusIcons.property, 'property'),
  IconDetails(OptimusIcons.queues_24, 'queues_24'),
  IconDetails(OptimusIcons.queues, 'queues'),
  IconDetails(OptimusIcons.quote_24, 'quote_24'),
  IconDetails(OptimusIcons.radio_empty_24, 'radio_empty_24'),
  IconDetails(OptimusIcons.radio_empty, 'radio_empty'),
  IconDetails(OptimusIcons.radio_selected_24, 'radio_selected_24'),
  IconDetails(OptimusIcons.rate_management_24, 'rate_management_24'),
  IconDetails(OptimusIcons.rate_management, 'rate_management'),
  IconDetails(OptimusIcons.rebate_24, 'rebate_24'),
  IconDetails(OptimusIcons.rebate, 'rebate'),
  IconDetails(OptimusIcons.refresh_24, 'refresh_24'),
  IconDetails(OptimusIcons.refresh, 'refresh'),
  IconDetails(OptimusIcons.refund_24, 'refund_24'),
  IconDetails(OptimusIcons.refund, 'refund'),
  IconDetails(OptimusIcons.report_bug_24, 'report_bug_24'),
  IconDetails(OptimusIcons.report_bug, 'report_bug'),
  IconDetails(OptimusIcons.reservation_group_24, 'reservation_group_24'),
  IconDetails(OptimusIcons.reservation_group, 'reservation_group'),
  IconDetails(OptimusIcons.reservation_overview_24, 'reservation_overview_24'),
  IconDetails(OptimusIcons.reservation_overview, 'reservation_overview'),
  IconDetails(OptimusIcons.reservation_preview_24, 'reservation_preview_24'),
  IconDetails(OptimusIcons.reservation_preview, 'reservation_preview'),
  IconDetails(
    OptimusIcons.reservation_properties_24,
    'reservation_properties_24',
  ),
  IconDetails(OptimusIcons.reservation_properties, 'reservation_properties'),
  IconDetails(OptimusIcons.reservation_report_24, 'reservation_report_24'),
  IconDetails(OptimusIcons.reservation_report, 'reservation_report'),
  IconDetails(OptimusIcons.reservations_24, 'reservations_24'),
  IconDetails(OptimusIcons.reservations, 'reservations'),
  IconDetails(OptimusIcons.reset_24, 'reset_24'),
  IconDetails(OptimusIcons.reset, 'reset'),
  IconDetails(OptimusIcons.restore_24, 'restore_24'),
  IconDetails(OptimusIcons.restore, 'restore'),
  IconDetails(OptimusIcons.restriction_24, 'restriction_24'),
  IconDetails(OptimusIcons.restriction, 'restriction'),
  IconDetails(OptimusIcons.return_24, 'return_24'),
  IconDetails(OptimusIcons.return_icon, 'return_icon'),
  IconDetails(OptimusIcons.returning_24, 'returning_24'),
  IconDetails(OptimusIcons.returning, 'returning'),
  IconDetails(OptimusIcons.room_24, 'room_24'),
  IconDetails(OptimusIcons.room, 'room'),
  IconDetails(OptimusIcons.scan_id_24, 'scan_id_24'),
  IconDetails(OptimusIcons.scan_id, 'scan_id'),
  IconDetails(OptimusIcons.scan_qr_24, 'scan_qr_24'),
  IconDetails(OptimusIcons.scan_qr, 'scan_qr'),
  IconDetails(OptimusIcons.scanner_24, 'scanner_24'),
  IconDetails(OptimusIcons.scanner, 'scanner'),
  IconDetails(OptimusIcons.schedules_24, 'schedules_24'),
  IconDetails(OptimusIcons.schedules, 'schedules'),
  IconDetails(OptimusIcons.search_24, 'search_24'),
  IconDetails(OptimusIcons.search, 'search'),
  IconDetails(OptimusIcons.security_24, 'security_24'),
  IconDetails(OptimusIcons.security, 'security'),
  IconDetails(OptimusIcons.send_message_24, 'send_message_24'),
  IconDetails(OptimusIcons.send_message, 'send_message'),
  IconDetails(OptimusIcons.service_order, 'service_order'),
  IconDetails(OptimusIcons.services_24, 'services_24'),
  IconDetails(OptimusIcons.services, 'services'),
  IconDetails(OptimusIcons.settings_24, 'settings_24'),
  IconDetails(OptimusIcons.settings_user_24, 'settings_user_24'),
  IconDetails(OptimusIcons.settings_user, 'settings_user'),
  IconDetails(OptimusIcons.settings, 'settings'),
  IconDetails(OptimusIcons.share_24, 'share_24'),
  IconDetails(OptimusIcons.share, 'share'),
  IconDetails(OptimusIcons.shared_data_24, 'shared_data_24'),
  IconDetails(OptimusIcons.shared_data, 'shared_data'),
  IconDetails(OptimusIcons.show_24, 'show_24'),
  IconDetails(OptimusIcons.show, 'show'),
  IconDetails(OptimusIcons.shrink_24, 'shrink_24'),
  IconDetails(OptimusIcons.shrink, 'shrink'),
  IconDetails(OptimusIcons.space_status_24, 'space_status_24'),
  IconDetails(OptimusIcons.space_status, 'space_status'),
  IconDetails(OptimusIcons.special_character_24, 'special_character_24'),
  IconDetails(OptimusIcons.special_character, 'special_character'),
  IconDetails(OptimusIcons.spent_nights_24, 'spent_nights_24'),
  IconDetails(OptimusIcons.spent_nights, 'spent_nights'),
  IconDetails(OptimusIcons.spinner_24, 'spinner_24'),
  IconDetails(OptimusIcons.spinner, 'spinner'),
  IconDetails(OptimusIcons.split_24, 'split_24'),
  IconDetails(OptimusIcons.split, 'split'),
  IconDetails(OptimusIcons.staff_24, 'staff_24'),
  IconDetails(OptimusIcons.staff, 'staff'),
  IconDetails(OptimusIcons.star_filled_24, 'star_filled_24'),
  IconDetails(OptimusIcons.star_filled, 'star_filled'),
  IconDetails(OptimusIcons.stars_24, 'stars_24'),
  IconDetails(OptimusIcons.stars, 'stars'),
  IconDetails(OptimusIcons.statistics_24, 'statistics_24'),
  IconDetails(OptimusIcons.statistics, 'statistics'),
  IconDetails(OptimusIcons.stayovers_24, 'stayovers_24'),
  IconDetails(OptimusIcons.stayovers, 'stayovers'),
  IconDetails(OptimusIcons.strikethrough_24, 'strikethrough_24'),
  IconDetails(OptimusIcons.subscription_24, 'subscription_24'),
  IconDetails(OptimusIcons.subscription, 'subscription'),
  IconDetails(OptimusIcons.summary_24, 'summary_24'),
  IconDetails(OptimusIcons.summary_order_24, 'summary_order_24'),
  IconDetails(OptimusIcons.summary_order, 'summary_order'),
  IconDetails(OptimusIcons.summary, 'summary'),
  IconDetails(OptimusIcons.switch_video_24, 'switch_video_24'),
  IconDetails(OptimusIcons.switch_video, 'switch_video'),
  IconDetails(OptimusIcons.targets_24, 'targets_24'),
  IconDetails(OptimusIcons.targets, 'targets'),
  IconDetails(OptimusIcons.task, 'task'),
  IconDetails(OptimusIcons.tasks_24, 'tasks_24'),
  IconDetails(OptimusIcons.tax_environment_24, 'tax_environment_24'),
  IconDetails(OptimusIcons.tax_environment, 'tax_environment'),
  IconDetails(OptimusIcons.team_area_24, 'team_area_24'),
  IconDetails(OptimusIcons.team_area, 'team_area'),
  IconDetails(OptimusIcons.tent_24, 'tent_24'),
  IconDetails(OptimusIcons.tent, 'tent'),
  IconDetails(OptimusIcons.terminal_24, 'terminal_24'),
  IconDetails(OptimusIcons.terminal_payment_24, 'terminal_payment_24'),
  IconDetails(OptimusIcons.terminal_payment, 'terminal_payment'),
  IconDetails(OptimusIcons.terminal, 'terminal'),
  IconDetails(OptimusIcons.text_align_center_24, 'text_align_center_24'),
  IconDetails(OptimusIcons.text_align_justify_24, 'text_align_justify_24'),
  IconDetails(OptimusIcons.text_align_left_24, 'text_align_left_24'),
  IconDetails(OptimusIcons.text_align_right_24, 'text_align_right_24'),
  IconDetails(OptimusIcons.text_line_height_24, 'text_line_height_24'),
  IconDetails(OptimusIcons.text_line_height, 'text_line_height'),
  IconDetails(OptimusIcons.thumbs_down_24, 'thumbs_down_24'),
  IconDetails(OptimusIcons.thumbs_down, 'thumbs_down'),
  IconDetails(OptimusIcons.thumbs_up_24, 'thumbs_up_24'),
  IconDetails(OptimusIcons.thumbs_up, 'thumbs_up'),
  IconDetails(OptimusIcons.time_24, 'time_24'),
  IconDetails(OptimusIcons.time, 'time'),
  IconDetails(OptimusIcons.timeline_24, 'timeline_24'),
  IconDetails(OptimusIcons.timeline_compact_24, 'timeline_compact_24'),
  IconDetails(OptimusIcons.timeline_compact, 'timeline_compact'),
  IconDetails(OptimusIcons.timeline_dense_24, 'timeline_dense_24'),
  IconDetails(OptimusIcons.timeline_dense, 'timeline_dense'),
  IconDetails(OptimusIcons.timeline_spacious_24, 'timeline_spacious_24'),
  IconDetails(OptimusIcons.timeline_spacious, 'timeline_spacious'),
  IconDetails(OptimusIcons.timeline, 'timeline'),
  IconDetails(OptimusIcons.toggle_left_24, 'toggle_left_24'),
  IconDetails(OptimusIcons.toggle_left, 'toggle_left'),
  IconDetails(OptimusIcons.toggle_right_24, 'toggle_right_24'),
  IconDetails(OptimusIcons.toggle_right, 'toggle_right'),
  IconDetails(OptimusIcons.top_management_24, 'top_management_24'),
  IconDetails(OptimusIcons.top_management, 'top_management'),
  IconDetails(OptimusIcons.train_24, 'train_24'),
  IconDetails(OptimusIcons.train, 'train'),
  IconDetails(OptimusIcons.travel_agency_24, 'travel_agency_24'),
  IconDetails(OptimusIcons.travel_agency, 'travel_agency'),
  IconDetails(OptimusIcons.travel_club_24, 'travel_club_24'),
  IconDetails(OptimusIcons.travel_club, 'travel_club'),
  IconDetails(OptimusIcons.travel_visa_24, 'travel_visa_24'),
  IconDetails(OptimusIcons.travel_visa, 'travel_visa'),
  IconDetails(OptimusIcons.trend_down, 'trend_down'),
  IconDetails(OptimusIcons.trend_up, 'trend_up'),
  IconDetails(OptimusIcons.tripadvisor_24, 'tripadvisor_24'),
  IconDetails(OptimusIcons.tripadvisor, 'tripadvisor'),
  IconDetails(OptimusIcons.twitter_24, 'twitter_24'),
  IconDetails(OptimusIcons.twitter, 'twitter'),
  IconDetails(OptimusIcons.underline_24, 'underline_24'),
  IconDetails(OptimusIcons.unlock_24, 'unlock_24'),
  IconDetails(OptimusIcons.unlock, 'unlock'),
  IconDetails(OptimusIcons.unpin_24, 'unpin_24'),
  IconDetails(OptimusIcons.unpin, 'unpin'),
  IconDetails(OptimusIcons.upgraded_24, 'upgraded_24'),
  IconDetails(OptimusIcons.upgraded, 'upgraded'),
  IconDetails(OptimusIcons.upload_24, 'upload_24'),
  IconDetails(OptimusIcons.upload, 'upload'),
  IconDetails(OptimusIcons.user_card_stack_24, 'user_card_stack_24'),
  IconDetails(OptimusIcons.user_card_stack, 'user_card_stack'),
  IconDetails(OptimusIcons.user_clock_24, 'user_clock_24'),
  IconDetails(OptimusIcons.user_clock, 'user_clock'),
  IconDetails(OptimusIcons.user_refresh_24, 'user_refresh_24'),
  IconDetails(OptimusIcons.user_refresh, 'user_refresh'),
  IconDetails(OptimusIcons.very_important_24, 'very_important_24'),
  IconDetails(OptimusIcons.very_important, 'very_important'),
  IconDetails(OptimusIcons.view_off_24, 'view_off_24'),
  IconDetails(OptimusIcons.view_off, 'view_off'),
  IconDetails(OptimusIcons.view_report_24, 'view_report_24'),
  IconDetails(OptimusIcons.view_report, 'view_report'),
  IconDetails(OptimusIcons.website_24, 'website_24'),
  IconDetails(OptimusIcons.website, 'website'),
  IconDetails(OptimusIcons.week, 'week'),
  IconDetails(OptimusIcons.wellness_24, 'wellness_24'),
  IconDetails(OptimusIcons.wellness, 'wellness'),
  IconDetails(OptimusIcons.window_24, 'window_24'),
  IconDetails(OptimusIcons.window, 'window'),
  IconDetails(OptimusIcons.mews_icon, 'mews_icon'),
  IconDetails(OptimusIcons.mews_favicon, 'mews_favicon'),
];
