version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/kiosk_mode/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/mews_pedantic/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/optimus/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/remote_logger/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/storybook/"
    ignore:
      # Relative dependencies that are always up to date
      - dependency-name: "mews_pedantic"
      - dependency-name: "optimus"
    schedule:
      interval: "monthly"
