name: Make initial setup
description: Run some initial setup scripts
runs:
  using: composite
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@ea686d7c56499339ad176e9f19c516ff6cf05a31
      with:
        flutter-version: 3.16.0
        cache: true

    - name: Set up environment paths
      shell: bash
      run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

    - name: Activate melos
      shell: bash
      run: dart pub global activate melos

    - name: Bootstrap
      shell: bash
      run: melos bs
