name: mews-flutter

packages:
  - '**'

scripts:
  check_master:
    run: |
      melos run format \
        && melos run pub_get \
        && melos run analyze \
        && melos run test --no-select

  analyze: |
    flutter analyze . \
      && melos exec -c 1 --ignore="*example*" -- "exec flutter pub run mews_pedantic:metrics analyze --fatal-style --fatal-performance --fatal-warnings lib"

  format: flutter format --set-exit-if-changed -n .

  pub_get: melos exec -c 1 --fail-fast -- "flutter pub get"

  build_runner: melos exec --scope="optimus" --fail-fast -- "exec flutter packages pub run build_runner build"

  test:
    run: melos exec -c 1 -- "flutter test --no-pub"
    select-package:
      dir-exists:
        - test
