name: mews-flutter

command:
  version:
    workspaceChangelog: false

scripts:
  gen_icons: 
    run: melos exec --scope="storybook" -- "dart utils/gen_icons.dart $MELOS_ROOT_PATH/optimus/lib/fonts/config/ lib/stories/icon && dart format lib/stories/icon/icons_list.dart"
    description: Generate the list of all icons for the storybook story
  gen_theme: 
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files

packages:
  - "**"
