name: Check PR to master
on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.0"

      - name: Set up environment paths
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Activate melos
        run: dart pub global activate melos

      - name: Bootstrap
        run: melos bs

      - name: Check formatting
        run: dart format --set-exit-if-changed -o none .

      - name: Built-in analyzer
        run: flutter analyze .

      - name: Test
        run: melos exec -c 1 --dir-exists="test" -- flutter test --no-pub

      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: .
