name: Check PR to master
on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install DCM
        run: >
          wget -qO- https://dcm.dev/pgp-key.public | sudo gpg --dearmor -o /usr/share/keyrings/dcm.gpg &&
          echo 'deb [signed-by=/usr/share/keyrings/dcm.gpg arch=amd64] https://dcm.dev/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list &&
          sudo apt-get update &&
          sudo apt-get install dcm

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.0"

      - name: Set up environment paths
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Activate melos
        run: dart pub global activate melos

      - name: Bootstrap
        run: melos bs

      - name: Check formatting
        run: dart format --set-exit-if-changed -o none .

      - name: Built-in analyzer
        run: flutter analyze .

      - name: Dart Code Metrics
        run: melos exec -c 1 --ignore="*example*" -- dcm analyze --fatal-style --fatal-performance --fatal-warnings --ci-key=${{ secrets.DCM_CI_KEY }} --email=${{ vars.DCM_CI_EMAIL }} .

      - name: Test
        run: melos exec -c 1 --dir-exists="test" -- flutter test --no-pub
