name: Check PR to master
on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Check formatting
        run: dart format --set-exit-if-changed -o none .

      - name: Built-in analyzer
        run: flutter analyze .
