name: Clean Widgetbook Azure Blob
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  clean-azure-blob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: List blobs before cleanup
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob list --account-name ${{ secrets.AZURE_ACCOUNT_NAME }} --container-name mews-ui-widgetbook --output table

      - name: Clean Widgetbook blob folder
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob delete-batch --source mews-ui-widgetbook --account-name ${{ secrets.AZURE_ACCOUNT_NAME }} --auth-mode login --pattern "*" --dryrun

      - name: List blobs after cleanup
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob list --account-name ${{ secrets.AZURE_ACCOUNT_NAME }} --container-name mews-ui-widgetbook --output table
