name: Publish mews_pedantic to pub.dev

on:
  push:
    tags:
      - "mews_pedantic-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    environment: pub.dev

    permissions:
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2

      - name: Install dependencies
        run: flutter pub get

      - name: Publish Dry Run
        run: flutter pub publish --directory=mews_pedantic --dry-run

      - name: Publish to pub.dev
        run: flutter pub publish --directory=mews_pedantic --force
