name: Publish remote_logger to pub.dev

on:
  push:
    tags:
      - "remote_logger-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    environment: pub.dev
    permissions:
      id-token: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/publish
        with:
          working-directory: remote_logger
